/**
 * Memory directory management and file I/O for agent/user memory system.
 * Used by ipc/memory.js and ipc/agent.js.
 */
const path = require('path')
const fs = require('fs')
const { logger } = require('../logger')
const ds = require('./dataStore')

function ensureAgentMemoryDirs(agentId) {
  const { AGENT_MEMORY_DIR } = ds.paths()
  const memDir  = path.join(AGENT_MEMORY_DIR, agentId)
  const logsDir = path.join(memDir, 'memory')
  fs.mkdirSync(logsDir, { recursive: true })
  return { memDir, logsDir }
}

function ensureUserMemoryDir(userId) {
  const { USER_MEMORY_DIR } = ds.paths()
  const userDir = path.join(USER_MEMORY_DIR, userId)
  fs.mkdirSync(userDir, { recursive: true })
  return userDir
}

function readMemoryFile(filePath) {
  try {
    if (fs.existsSync(filePath)) return fs.readFileSync(filePath, 'utf8')
  } catch (err) {
    logger.error('readMemoryFile error', err.message)
  }
  return null
}

function appendMemoryFile(filePath, text) {
  try {
    fs.mkdirSync(path.dirname(filePath), { recursive: true })
    fs.appendFileSync(filePath, text, 'utf8')
  } catch (err) {
    logger.error('appendMemoryFile error', err.message)
  }
}

function appendMemoryEntry(agentId, userId, target, section, entry) {
  try {
    const { AGENT_MEMORY_DIR, USER_MEMORY_DIR } = ds.paths()
    let filePath
    if (target === 'user') {
      const userDir = path.join(USER_MEMORY_DIR, userId)
      fs.mkdirSync(userDir, { recursive: true })
      filePath = path.join(userDir, 'USER.md')
    } else {
      const agentDir = path.join(AGENT_MEMORY_DIR, agentId)
      fs.mkdirSync(agentDir, { recursive: true })
      filePath = path.join(agentDir, 'MEMORY.md')
    }

    if (!fs.existsSync(filePath)) {
      const header = target === 'user'
        ? `# User Profile\n> Auto-generated by ClanKit\n\n`
        : `# Knowledge Base\n> Auto-generated by ClanKit\n\n`
      fs.writeFileSync(filePath, header, 'utf8')
    }

    let content = fs.readFileSync(filePath, 'utf8')
    const sectionHeader = `## ${section}`
    if (!content.includes(sectionHeader)) {
      content += `\n${sectionHeader}\n\n`
    }
    content += `- ${entry}\n`
    fs.writeFileSync(filePath, content, 'utf8')
  } catch (err) {
    logger.error('appendMemoryEntry error', err.message)
  }
}

function getAgentLogPaths(agentId) {
  const { logsDir } = ensureAgentMemoryDirs(agentId)
  const now   = new Date()
  const today = now.toISOString().slice(0, 10)
  const yest  = new Date(now - 86400000).toISOString().slice(0, 10)
  return {
    todayPath:     path.join(logsDir, `${today}.md`),
    yesterdayPath:  path.join(logsDir, `${yest}.md`),
  }
}

module.exports = {
  ensureAgentMemoryDirs,
  ensureUserMemoryDir,
  readMemoryFile,
  appendMemoryFile,
  appendMemoryEntry,
  getAgentLogPaths,
}
